{% set name = "mattspy" %}
{% set version = "0.76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: d3aaf258b23648f923beb12511c31223b2925aaeb6f7bf1340d8350c5729b69d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - pip
    - setuptools_scm >=7
  run:
    - python >={{ python_min }}
    - cloudpickle
    - numpy
    - joblib
    - loky
    - scipy
    - esutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task
    - python -c "import mattspy; assert mattspy.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
