{% set name = "mattspy" %}
{% set version = "0.75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/mattspy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 75a3ec1dae95d9035d70fd12778f0a4c93b433e9af3f98a502ac7df47b4dc2d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mattspy-exec-run-pickled-task = mattspy.mattspy_exec_run:run_pickled_task

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - cloudpickle
    - numpy
    - joblib
    - importlib-metadata
    - loky
    - scipy
    - esutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - mattspy
  commands:
    - command -v mattspy-exec-run-pickled-task

about:
  home: https://github.com/beckermr/mattspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: my personal python utils

extra:
  recipe-maintainers:
    - beckermr
